In [1]:
import seaborn as sns
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Total Defense Crawl

In [2]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/total'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [3]:
# stat_table =soup.find_all('table', class_ = "Table2__table-scroller Table2__right-aligned Table2__table")
stat_table =soup.find_all('table', class_ = "Table Table--align-right")
len(stat_table)

#name_table = soup.find_all('table', class_="Table2__right-aligned Table2__table-fixed Table2__Table--fixed--left Table2__table")
name_table = soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [4]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
team_names

# Need to remove some columns
stat_headers = stat_headers[5:]
stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[2:]
team_stats

['New England Patriots',
 'San Francisco 49ers',
 'Buffalo Bills',
 'Pittsburgh Steelers',
 'Los Angeles Chargers',
 'Baltimore Ravens',
 'Dallas Cowboys',
 'Chicago Bears',
 'New York Jets',
 'New Orleans Saints',
 'Philadelphia Eagles',
 'Los Angeles Rams',
 'Denver Broncos',
 'Minnesota Vikings',
 'Tampa Bay Buccaneers',
 'Indianapolis Colts',
 'Cleveland Browns',
 'Kansas City Chiefs',
 'Tennessee Titans',
 'Atlanta Falcons',
 'Washington Redskins',
 'Oakland Raiders',
 'Green Bay Packers',
 'Jacksonville Jaguars',
 'New York Giants',
 'Carolina Panthers',
 'Seattle Seahawks',
 'Houston Texans',
 'Cincinnati Bengals',
 'Miami Dolphins',
 'Detroit Lions',
 'Arizona Cardinals']

['GP', 'YDS', 'YDS/G', 'YDS', 'YDS/G', 'YDS', 'YDS/G', 'PTS', 'PTS/G']

[['14', '3,757', '268.4', '2,384', '170.3', '1,373', '98.1', '181', '12.9'],
 ['14', '3,766', '269.0', '2,161', '154.4', '1,605', '114.6', '258', '18.4'],
 ['14', '4,087', '291.9', '2,667', '190.5', '1,420', '101.4', '222', '15.9'],
 ['14', '4,303', '307.4', '2,858', '204.1', '1,445', '103.2', '259', '18.5'],
 ['14', '4,307', '307.6', '2,763', '197.4', '1,544', '110.3', '290', '20.7'],
 ['14', '4,400', '314.3', '3,054', '218.1', '1,346', '96.1', '257', '18.4'],
 ['14', '4,530', '323.6', '3,080', '220.0', '1,450', '103.6', '288', '20.6'],
 ['14', '4,536', '324.0', '3,184', '227.4', '1,352', '96.6', '253', '18.1'],
 ['14', '4,601', '328.6', '3,358', '239.9', '1,243', '88.8', '343', '24.5'],
 ['14', '4,603', '328.8', '3,332', '238.0', '1,271', '90.8', '303', '21.6'],
 ['14', '4,609', '329.2', '3,343', '238.8', '1,266', '90.4', '328', '23.4'],
 ['14', '4,707', '336.2', '3,088', '220.6', '1,619', '115.6', '306', '21.9'],
 ['14', '4,724', '337.4', '3,134', '223.9', '1,590', '113.6', '284', '20.3'],
 ['14', '4,745', '338.9', '3,359', '239.9', '1,386', '99.0', '259', '18.5'],
 ['14', '4,901', '350.1', '3,875', '276.8', '1,026', '73.3', '398', '28.4'],
 ['14', '4,910', '350.7', '3,497', '249.8', '1,413', '100.9', '329', '23.5'],
 ['14', '4,943', '353.1', '3,050', '217.9', '1,893', '135.2', '329', '23.5'],
 ['14', '4,994', '356.7', '3,152', '225.1', '1,842', '131.6', '284', '20.3'],
 ['14', '5,074', '362.4', '3,613', '258.1', '1,461', '104.4', '279', '19.9'],
 ['14', '5,076', '362.6', '3,552', '253.7', '1,524', '108.9', '365', '26.1'],
 ['14', '5,093', '363.8', '3,183', '227.4', '1,910', '136.4', '347', '24.8'],
 ['14', '5,155', '368.2', '3,674', '262.4', '1,481', '105.8', '386', '27.6'],
 ['14', '5,198', '371.3', '3,505', '250.4', '1,693', '120.9', '283', '20.2'],
 ['14', '5,214', '372.4', '3,252', '232.3', '1,962', '140.1', '353', '25.2'],
 ['14', '5,276', '376.9', '3,665', '261.8', '1,611', '115.1', '382', '27.3'],
 ['14', '5,289', '377.8', '3,326', '237.6', '1,963', '140.2', '390', '27.9'],
 ['14', '5,296', '378.3', '3,794', '271.0', '1,502', '107.3', '345', '24.6'],
 ['14', '5,311', '379.4', '3,725', '266.1', '1,586', '113.3', '330', '23.6'],
 ['14', '5,484', '391.7', '3,272', '233.7', '2,212', '158.0', '359', '25.6'],
 ['14', '5,582', '398.7', '3,610', '257.9', '1,972', '140.9', '435', '31.1'],
 ['14', '5,626', '401.9', '4,041', '288.6', '1,585', '113.2', '373', '26.6'],
 ['14', '5,784', '413.1', '4,066', '290.4', '1,718', '122.7', '398', '28.4']]

In [5]:
# Create a DataFrame

total_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
total_defense_stats['Team'] = team_names
total_defense_stats.set_index('Team', inplace = True)

In [6]:
total_defense_stats

                      GP    YDS  YDS/G    YDS  YDS/G    YDS  YDS/G  PTS PTS/G
Team
New England Patriots  14  3,757  268.4  2,384  170.3  1,373   98.1  181  12.9
San Francisco 49ers   14  3,766  269.0  2,161  154.4  1,605  114.6  258  18.4
Buffalo Bills         14  4,087  291.9  2,667  190.5  1,420  101.4  222  15.9
Pittsburgh Steelers   14  4,303  307.4  2,858  204.1  1,445  103.2  259  18.5
Los Angeles Chargers  14  4,307  307.6  2,763  197.4  1,544  110.3  290  20.7
...                   ..    ...    ...    ...    ...    ...    ...  ...   ...
Houston Texans        14  5,311  379.4  3,725  266.1  1,586  113.3  330  23.6
Cincinnati Bengals    14  5,484  391.7  3,272  233.7  2,212  158.0  359  25.6
Miami Dolphins        14  5,582  398.7  3,610  257.9  1,972  140.9  435  31.1
Detroit Lions         14  5,626  401.9  4,041  288.6  1,585  113.2  373  26.6
Arizona Cardinals     14  5,784  413.1  4,066  290.4  1,718  122.7  398  28.4

[32 rows x 9 columns]

# Passing Defense Crawl

In [7]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/passing'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [8]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [9]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [10]:
# Create a DataFrame

passing_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
passing_defense_stats['Team'] = team_names
passing_defense_stats.set_index('Team', inplace = True)

In [11]:
passing_defense_stats

,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,RTG
Team,,,,,,,,,,,,,
San Francisco 49ers,14,266,433,61.4,"2,161",5.8,154.4,88,19,11,47,357,81.5
New England Patriots,14,261,466,56.0,"2,384",5.7,170.3,64,10,25,41,282,57.4
Buffalo Bills,14,299,484,61.8,"2,667",6.1,190.5,61,13,13,42,284,76.7
Los Angeles Chargers,14,286,409,69.9,"2,763",7.2,197.4,70,19,10,27,166,95.5
Pittsburgh Steelers,14,287,467,61.5,"2,858",6.8,204.1,58,22,19,49,318,80.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Houston Texans,14,336,517,65.0,"3,725",7.6,266.1,65,30,8,28,209,100.8
Seattle Seahawks,14,350,549,63.8,"3,794",7.2,271.0,58,18,16,24,161,84.0
Tampa Bay Buccaneers,14,359,581,61.8,"3,875",7.1,276.8,75,29,11,36,275,92.1
Detroit Lions,14,328,522,62.8,"4,041",8.1,288.6,66,30,6,27,177,102.5
Arizona Cardinals,14,376,525,71.6,"4,066",8.2,290.4,57,34,7,34,231,111.9

# Rushing Defense Crawl

In [12]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/rushing'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [13]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [14]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [15]:
# Create a DataFrame

rushing_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
rushing_defense_stats['Team'] = team_names
rushing_defense_stats.set_index('Team', inplace = True)

In [16]:
rushing_defense_stats

                      GP  ATT    YDS  AVG  YDS/G LNG  TD FUM LST
Team
Tampa Bay Buccaneers  14  306  1,026  3.4   73.3  59  10   5   3
New York Jets         14  372  1,243  3.3   88.8  66  12   7   2
Philadelphia Eagles   14  317  1,266  4.0   90.4  58  12   6   4
New Orleans Saints    14  301  1,271  4.2   90.8  32  10   6   5
Baltimore Ravens      14  298  1,346  4.5   96.1  88  11   3   0
...                   ..  ...    ...  ...    ...  ..  ..  ..  ..
Washington Redskins   14  431  1,910  4.4  136.4  56  12   7   3
Jacksonville Jaguars  14  381  1,962  5.2  140.1  84  19   5   2
Carolina Panthers     14  378  1,963  5.2  140.2  60  26   5   2
Miami Dolphins        14  433  1,972  4.6  140.9  60  14   8   1
Cincinnati Bengals    14  450  2,212  4.9  158.0  57  16   5   2

[32 rows x 9 columns]

# Receiving Offense Stats

In [17]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/receiving'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [18]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [19]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [20]:
# Create a DataFrame

receiving_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
receiving_defense_stats['Team'] = team_names
receiving_defense_stats.set_index('Team', inplace = True)

In [21]:
receiving_defense_stats

                      GP  REC    YDS   AVG  YDS/G LNG  TD FUM LST
Team
San Francisco 49ers   14  266  2,518   9.5  179.9  88  19   5   4
New England Patriots  14  261  2,666  10.2  190.4  64  10   6   3
Los Angeles Chargers  14  286  2,929  10.2  209.2  70  19   1   0
Buffalo Bills         14  299  2,951   9.9  210.8  61  13   8   5
Pittsburgh Steelers   14  287  3,176  11.1  226.9  58  22   3   2
...                   ..  ...    ...   ...    ...  ..  ..  ..  ..
Houston Texans        14  336  3,934  11.7  281.0  65  30   1   0
Seattle Seahawks      14  350  3,955  11.3  282.5  58  18   6   3
Tampa Bay Buccaneers  14  359  4,150  11.6  296.4  75  29   5   4
Detroit Lions         14  328  4,218  12.9  301.3  66  30   4   2
Arizona Cardinals     14  376  4,297  11.4  306.9  57  34   4   2

[32 rows x 9 columns]

In [22]:
#!mkdir week1

In [23]:
total_defense_stats.to_csv('./week15/total_defense')
passing_defense_stats.to_csv('./week15/passing_defense')
rushing_defense_stats.to_csv('./week15/rushing_defense')
receiving_defense_stats.to_csv('./week15/receiving_defense')

In [24]:
print('Fertig')

Fertig