In [4]:
import pandas as pd

In [41]:
dfs = pd.read_excel('./csv/fantasy2020rankingsexcel.xlsx', sheet_name=['QBs', 'RBs', 'WRs', 'TEs', 'Ks'])

In [42]:
keeys = dfs.keys()

In [43]:
ddfs = []

for key in keeys:
    d = ddfs.append(dfs[key])

In [45]:
pd.concat(ddfs, axis=0)

,Last Name,First Name,Team,Bye,Pos,PASS YDS,PASS TD,INT,RUSH YDS,CATCH,REC YDS,REG TD,Bonus,Dynst,Points (ESPN Scoring),...,WRs,WRs.1,POINTS,VBD PPR,Tes,Tes.1,FG 1-39,FG 40-49,FG 50+,XP,2QB POINTS,POINTS (Custom),Unnamed: 19,Ks,Ks.1
0,Mahomes,Patrick,Chiefs,10.0,QB,4700.0,42.0,6.0,250.0,NaN,NaN,3.0,-20.0,18.0,367.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jackson,Lamar,Ravens,8.0,QB,3300.0,29.0,8.0,1080.0,NaN,NaN,7.0,-20.0,15.0,362.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wilson,Russell,Seahawks,6.0,QB,4100.0,32.0,6.0,340.0,NaN,NaN,3.0,-10.0,5.0,322.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Watson,Deshaun,Texans,8.0,QB,4000.0,25.0,12.0,430.0,NaN,NaN,5.0,-5.0,18.0,304.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Murray,Kyler,Cardinals,8.0,QB,4100.0,24.0,13.0,470.0,NaN,NaN,4.0,-3.0,15.0,302.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,Sanders,Jason,Dolphins,NaN,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,112.0,-65.0,NaN,NaN,15.0,6.0,2.0,33.0,112.0,112.0,NaN,NaN,NaN
28,Slye,Joey,Panthers,NaN,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,111.0,-66.0,NaN,NaN,13.0,8.0,3.0,25.0,111.0,111.0,NaN,NaN,NaN
29,Pineiro,Eddy,Bears,NaN,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,110.0,-67.0,NaN,NaN,16.0,5.0,2.0,32.0,110.0,110.0,NaN,NaN,NaN
30,Joseph,Greg,Titans,NaN,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,107.0,-70.0,NaN,NaN,16.0,6.0,1.0,30.0,107.0,107.0,NaN,NaN,NaN
31,Rohrwasser,Justin,Patriots,NaN,K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,106.0,-71.0,NaN,NaN,15.0,4.0,2.0,35.0,106.0,106.0,NaN,NaN,NaN