In [14]:
import cufflinks as cf
import plotly.offline
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

import seaborn as sns
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Total Defense Crawl

In [15]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/total'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [16]:
# stat_table =soup.find_all('table', class_ = "Table2__table-scroller Table2__right-aligned Table2__table")
stat_table =soup.find_all('table', class_ = "Table Table--align-right")
len(stat_table)

#name_table = soup.find_all('table', class_="Table2__right-aligned Table2__table-fixed Table2__Table--fixed--left Table2__table")
name_table = soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [17]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
team_names

# Need to remove some columns
stat_headers = stat_headers[5:]
stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[2:]
team_stats

['New England Patriots',
 'San Francisco 49ers',
 'Los Angeles Rams',
 'Carolina Panthers',
 'Buffalo Bills',
 'Tennessee Titans',
 'Atlanta Falcons',
 'Chicago Bears',
 'Denver Broncos',
 'Cleveland Browns',
 'Seattle Seahawks',
 'Minnesota Vikings',
 'Green Bay Packers',
 'Tampa Bay Buccaneers',
 'Dallas Cowboys',
 'Philadelphia Eagles',
 'Baltimore Ravens',
 'Indianapolis Colts',
 'Los Angeles Chargers',
 'Jacksonville Jaguars',
 'New York Jets',
 'Houston Texans',
 'Detroit Lions',
 'Kansas City Chiefs',
 'Oakland Raiders',
 'Washington Redskins',
 'Cincinnati Bengals',
 'New Orleans Saints',
 'Pittsburgh Steelers',
 'Arizona Cardinals',
 'New York Giants',
 'Miami Dolphins']

['GP', 'YDS', 'YDS/G', 'YDS', 'YDS/G', 'YDS', 'YDS/G', 'PTS', 'PTS/G']

[['3', '597', '199.0', '487', '162.3', '110', '36.7', '17', '5.7'],
 ['3', '850', '283.3', '625', '208.3', '225', '75.0', '54', '18.0'],
 ['3', '857', '285.7', '578', '192.7', '279', '93.0', '49', '16.3'],
 ['3', '886', '295.3', '499', '166.3', '387', '129.0', '70', '23.3'],
 ['3', '899', '299.7', '635', '211.7', '264', '88.0', '47', '15.7'],
 ['3', '926', '308.7', '569', '189.7', '357', '119.0', '52', '17.3'],
 ['3', '934', '311.3', '634', '211.3', '300', '100.0', '75', '25.0'],
 ['3', '941', '313.7', '735', '245.0', '206', '68.7', '39', '13.0'],
 ['3', '942', '314.0', '614', '204.7', '328', '109.3', '67', '22.3'],
 ['3', '946', '315.3', '640', '213.3', '306', '102.0', '66', '22.0'],
 ['3', '955', '318.3', '752', '250.7', '203', '67.7', '79', '26.3'],
 ['3', '982', '327.3', '677', '225.7', '305', '101.7', '47', '15.7'],
 ['3', '985', '328.3', '592', '197.3', '393', '131.0', '35', '11.7'],
 ['3', '992', '330.7', '783', '261.0', '209', '69.7', '77', '25.7'],
 ['3', '1,008', '336.0', '738', '246.0', '270', '90.0', '44', '14.7'],
 ['3', '1,052', '350.7', '881', '293.7', '171', '57.0', '78', '26.0'],
 ['3', '1,052', '350.7', '871', '290.3', '181', '60.3', '60', '20.0'],
 ['3', '1,075', '358.3', '733', '244.3', '342', '114.0', '71', '23.7'],
 ['3', '1,091', '363.7', '755', '251.7', '336', '112.0', '64', '21.3'],
 ['3', '1,094', '364.7', '764', '254.7', '330', '110.0', '60', '20.0'],
 ['3', '1,126', '375.3', '860', '286.7', '266', '88.7', '70', '23.3'],
 ['3', '1,157', '385.7', '833', '277.7', '324', '108.0', '62', '20.7'],
 ['3', '1,184', '394.7', '808', '269.3', '376', '125.3', '61', '20.3'],
 ['3', '1,187', '395.7', '774', '258.0', '413', '137.7', '64', '21.3'],
 ['3', '1,196', '398.7', '859', '286.3', '337', '112.3', '78', '26.0'],
 ['3', '1,208', '402.7', '782', '260.7', '426', '142.0', '94', '31.3'],
 ['3', '1,219', '406.3', '713', '237.7', '506', '168.7', '83', '27.7'],
 ['3', '1,309', '436.3', '905', '301.7', '404', '134.7', '82', '27.3'],
 ['3', '1,326', '442.0', '908', '302.7', '418', '139.3', '85', '28.3'],
 ['3', '1,330', '443.3', '859', '286.3', '471', '157.0', '88', '29.3'],
 ['3', '1,381', '460.3', '997', '332.3', '384', '128.0', '94', '31.3'],
 ['3', '1,498', '499.3', '874', '291.3', '624', '208.0', '133', '44.3']]

In [18]:
# Create a DataFrame

total_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
total_defense_stats['Team'] = team_names
total_defense_stats.set_index('Team', inplace = True)

In [19]:
total_defense_stats

                     GP    YDS  YDS/G  YDS  YDS/G  YDS  YDS/G  PTS PTS/G
Team
New England Patriots  3    597  199.0  487  162.3  110   36.7   17   5.7
San Francisco 49ers   3    850  283.3  625  208.3  225   75.0   54  18.0
Los Angeles Rams      3    857  285.7  578  192.7  279   93.0   49  16.3
Carolina Panthers     3    886  295.3  499  166.3  387  129.0   70  23.3
Buffalo Bills         3    899  299.7  635  211.7  264   88.0   47  15.7
...                  ..    ...    ...  ...    ...  ...    ...  ...   ...
New Orleans Saints    3  1,309  436.3  905  301.7  404  134.7   82  27.3
Pittsburgh Steelers   3  1,326  442.0  908  302.7  418  139.3   85  28.3
Arizona Cardinals     3  1,330  443.3  859  286.3  471  157.0   88  29.3
New York Giants       3  1,381  460.3  997  332.3  384  128.0   94  31.3
Miami Dolphins        3  1,498  499.3  874  291.3  624  208.0  133  44.3

[32 rows x 9 columns]

# Passing Defense Crawl

In [20]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/passing'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [21]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [22]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [23]:
# Create a DataFrame

passing_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
passing_defense_stats['Team'] = team_names
passing_defense_stats.set_index('Team', inplace = True)

In [24]:
passing_defense_stats

,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,RTG
Team,,,,,,,,,,,,,
New England Patriots,3,57,108,52.8,487,5.2,162.3,45,0,6,13,73,44.5
Carolina Panthers,3,69,107,64.5,499,5.3,166.3,41,4,3,12,68,78.7
Tennessee Titans,3,62,96,64.6,569,6.6,189.7,37,6,4,8,66,86.9
Los Angeles Rams,3,63,109,57.8,578,5.8,192.7,30,1,3,8,59,66.2
Green Bay Packers,3,60,106,56.6,592,6.3,197.3,61,1,4,12,79,63.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Miami Dolphins,3,62,86,72.1,874,10.3,291.3,83,10,1,4,15,139.1
Philadelphia Eagles,3,75,119,63.0,881,7.6,293.7,69,7,3,2,20,95.3
New Orleans Saints,3,71,108,65.7,905,8.9,301.7,66,6,1,9,52,108.5
Pittsburgh Steelers,3,77,104,74.0,908,9.1,302.7,58,7,2,6,42,116.3
New York Giants,3,67,99,67.7,997,10.5,332.3,62,8,1,7,41,124.9

# Rushing Defense Crawl

In [25]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/rushing'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [26]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [27]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [28]:
# Create a DataFrame

rushing_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
rushing_defense_stats['Team'] = team_names
rushing_defense_stats.set_index('Team', inplace = True)

In [29]:
rushing_defense_stats

                     GP  ATT  YDS  AVG  YDS/G LNG TD FUM LST
Team
New England Patriots  3   48  110  2.3   36.7   9  0   0   0
Philadelphia Eagles   3   58  171  2.9   57.0  44  1   0   0
Baltimore Ravens      3   49  181  3.7   60.3  41  2   2   0
Seattle Seahawks      3   53  203  3.8   67.7  23  2   0   0
Chicago Bears         3   67  206  3.1   68.7  14  0   2   1
...                  ..  ...  ...  ...    ...  .. ..  ..  ..
Pittsburgh Steelers   3  102  418  4.1  139.3  37  3   5   4
Washington Redskins   3   89  426  4.8  142.0  42  2   0   0
Arizona Cardinals     3   96  471  4.9  157.0  76  1   0   0
Cincinnati Bengals    3  103  506  4.9  168.7  34  4   2   1
Miami Dolphins        3  115  624  5.4  208.0  60  6   1   1

[32 rows x 9 columns]

# Receiving Offense Stats

In [30]:
url ='https://www.espn.com/nfl/stats/team/_/view/defense/stat/receiving'

headers= {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url)
print(response.status_code)

soup = BeautifulSoup(response.content, 'html.parser')

200

In [31]:
name_table =soup.find_all('table', class_="Table Table--align-right Table--fixed Table--fixed-left")
len(name_table)

stat_table = soup.find_all('table', class_="Table Table--align-right")
len(stat_table)

stat_table = stat_table[0]
name_table = name_table[0]

1

1

In [32]:
team_names = []
stat_headers = []
team_stats = []
temp = []

for row in name_table.find_all('tr'):
    for cell in row.find_all('td'):
        #print(cell.text)
        team_names.append(cell.text)

for row in stat_table.find_all('tr'):
    #print(cell.text)
    for cell in row.find_all('th'):
            #print(cell.text)
            stat_headers.append(cell.text)        

for row in stat_table.find_all('tr'):
    for cell in row.find_all('td'):
        temp.append(cell.text)
    team_stats.append(temp)
    temp = []
            
# print team names
#team_names

# Need to remove some columns
#stat_headers

# Team stats - First two empty lists items need to be removed
team_stats = team_stats[1:]
#team_stats

In [33]:
# Create a DataFrame

receiving_defense_stats = pd.DataFrame(team_stats, columns=stat_headers)
receiving_defense_stats['Team'] = team_names
receiving_defense_stats.set_index('Team', inplace = True)

In [34]:
receiving_defense_stats

                     GP REC    YDS   AVG  YDS/G LNG TD FUM LST
Team
New England Patriots  3  57    560   9.8  186.7  45  0   0   0
Carolina Panthers     3  69    567   8.2  189.0  41  4   0   0
Denver Broncos        3  55    614  11.2  204.7  43  2   0   0
Tennessee Titans      3  62    635  10.2  211.7  37  6   0   0
Los Angeles Rams      3  63    637  10.1  212.3  30  1   1   1
...                  ..  ..    ...   ...    ...  .. ..  ..  ..
Baltimore Ravens      3  67    913  13.6  304.3  83  4   1   0
Arizona Cardinals     3  70    918  13.1  306.0  52  9   1   0
Pittsburgh Steelers   3  77    950  12.3  316.7  58  7   0   0
New Orleans Saints    3  71    957  13.5  319.0  66  6   0   0
New York Giants       3  67  1,038  15.5  346.0  62  8   0   0

[32 rows x 9 columns]

In [35]:
#!mkdir week1

In [36]:
total_defense_stats.to_csv('./week4/total_defense')
passing_defense_stats.to_csv('./week4/passing_defense')
rushing_defense_stats.to_csv('./week4/rushing_defense')
receiving_defense_stats.to_csv('./week4/receiving_defense')