# NFL Offense Data Analysis

This notebook is part of one of my **NFL Crawl** project and contains the *data engineering* part.  
Mainly it is about using the crawled data and set them up for the graphical analysis which will follow in another notebook.

The used `.csv-files` are, as already described, the crawled datasets from the *ESPN* website.
The notebooks can be found in the same repository under the creative names [offense]() and [defense]().

## Importing the csv files

In [1]:
# Import passing offense
week1_pass_offense = pd.read_csv('./week1/passing_offense')
week1_pass_offense.set_index('Team', inplace=True)
week2_pass_offense = pd.read_csv('./week2/passing_offense')
week2_pass_offense.set_index('Team', inplace=True)
week3_pass_offense = pd.read_csv('./week3/passing_offense')
week3_pass_offense.set_index('Team', inplace=True)
week4_pass_offense = pd.read_csv('./week4/passing_offense')
week4_pass_offense.set_index('Team', inplace=True)

# Import rushing offense
week1_rush_offense = pd.read_csv('./week1/rushing_offense')
week1_rush_offense.set_index('Team', inplace=True)
week2_rush_offense = pd.read_csv('./week2/rushing_offense')
week2_rush_offense.set_index('Team', inplace=True)
week3_rush_offense = pd.read_csv('./week3/rushing_offense')
week3_rush_offense.set_index('Team', inplace=True)
week4_rush_offense = pd.read_csv('./week4/rushing_offense')
week4_rush_offense.set_index('Team', inplace=True)

In [2]:
# Import the score-table
scores = pd.read_csv('games.csv', delimiter=';')
scores.set_index('teamname', inplace=True)
scores_transpose = scores.transpose()
scores_transpose

teamname,ArizonaCardinals,AtlantaFalcons,BaltimoreRavens,BuffaloBills,CarolinaPanthers,ChicagoBears,CincinnatiBengals,ClevelandBrowns,DallasCowboys,DenverBroncos,DetroitLions,GreenBayPackers,HoustonTexans,IndianapolisColts,JacksonvilleJaguars,...,LosAngelesRams,MiamiDolphins,MinnesotaVikings,NewEnglandPatriots,NewOrleansSaints,NewYorkGiants,NewYorkJets,OaklandRaiders,PhiladelphiaEagles,PittsburghSteelers,SanFrancisco49ers,SeattleSeahawks,TampaBayBuccaneers,TennesseeTitans,WashingtonRedskins
week1,2,0,1,1,0,0,0,0,1,0,2,1,0,0,0,...,1,0,1,1,1,0,0,1,1,0,1,1,0,1,0
week2,0,1,1,1,0,1,0,1,1,0,1,1,1,1,0,...,1,0,0,1,0,0,0,0,0,0,1,1,1,0,0
week3,0,0,0,1,1,1,0,0,1,0,1,1,1,1,1,...,1,0,1,1,1,1,0,0,0,0,1,0,0,0,0
week4,0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,...,0,0,0,1,1,1,3,1,1,1,3,1,1,1,0

The `score` table contains information about the result of each game.
The numbers within this table can be interpreted as follows:
* 0 = Lost the game
* 1 = Won the game
* 2 = Tie
* 3 = Bye-Week

I needed to transpose the date because later the weeks are `indices` when it comes to the table-per-team.

In [9]:
team_names = pd.read_csv('nflnames.csv')
team_names = list(team_names.team_name)
team_list = []
for team in team_names:
    team_list.append(team.replace(" ", ""))

A simple list of all 32 NFL Teams. I erased the whitespaces for asthetic reasons and it makes it easier to use the names later.

## Combine tables

In [3]:
# Creating list containing all of the used data
rush = [week1_rush_offense, week2_rush_offense, week3_rush_offense, week4_rush_offense]
passing = [week1_pass_offense, week2_pass_offense, week3_pass_offense, week4_pass_offense]

In [4]:
# GP was in both combined tables and therfore needs to be deleted once
new_rush = []
for i in rush:
    i.drop('GP', axis=1, inplace=True)
    new_rush.append(i)

In [5]:
def concat_dfs(passing, rushing):
    for i in range(4):
        globals()['week%s' % i] = pd.concat([passing[i], rush[i]], axis=1, sort=True)

In [6]:
concat_dfs(passing, new_rush)

**NOTE: The given tables from week1 to weekXY are all ordered by name! This makes it possible to iter through the table and always get the same sequence of teams!**

This function will get important as soon as we create DF's for each NFL Team

A bit a pain in the ass but I was too lazy to write a function which always collects the available weeks.

In [7]:
weeks = [week0, week1, week2, week3]

## Create a dictionary per team and week

In [10]:
def filter_per_team(weeks):
    
    temp_week_buffer = []
    team_dict = {}
    
    
    for team in range(32):
        for week in weeks:
            temp_week_buffer.append(list(week.iloc[team]))
        team_dict[team] = temp_week_buffer
        temp_week_buffer = []
        
    return(team_dict)

In [11]:
results_by_team = filter_per_team(weeks)

**Important Setp:**  
Here the names of the dictionary keys are changed to the actual team names.

In [12]:
i = 0
for name in team_list:
    results_by_team[name] = results_by_team.pop(i)
    i+=1

In [13]:
results_df = pd.DataFrame.from_dict(results_by_team, orient='index')

In [14]:
results_df.head()

,0,1,2,3
ArizonaCardinals,"[1.0, 29.0, 54.0, 53.7, 275.0, 5.7, 275.0, 45....","[2.0, 54.0, 94.0, 57.4, 604.0, 7.0, 302.0, 54....","[3, 84, 137, 61.3, 731, 6.1, 243.7, 54, 4, 3, ...","[4, 106, 169, 62.7, 937, 6.3, 234.3, 54, 4, 4,..."
AtlantaFalcons,"[1.0, 33.0, 46.0, 71.7, 272.0, 6.6, 272.0, 23....","[2.0, 60.0, 89.0, 67.4, 582.0, 7.0, 291.0, 54....","[3, 89, 123, 72.4, 886, 7.5, 295.3, 54, 8, 6, ...","[4, 124, 176, 70.5, 1,250, 7.5, 312.5, 54, 8, ..."
BaltimoreRavens,"[1.0, 23.0, 26.0, 88.5, 378.0, 14.6, 378.0, 83...","[2.0, 47.0, 63.0, 74.6, 636.0, 10.3, 318.0, 83...","[3, 69, 106, 65.1, 885, 8.7, 295.0, 83, 8, 0, ...","[4, 93, 140, 66.4, 1,107, 8.3, 276.8, 83, 11, ..."
BuffaloBills,"[1.0, 24.0, 37.0, 64.9, 242.0, 6.9, 242.0, 38....","[2.0, 43.0, 67.0, 64.2, 479.0, 7.6, 239.5, 51....","[3, 66, 103, 64.1, 720, 7.3, 240.0, 51, 3, 3, ...","[4, 88, 147, 59.9, 960, 7.0, 240.0, 51, 3, 7, ..."
CarolinaPanthers,"[1.0, 25.0, 38.0, 65.8, 216.0, 6.3, 216.0, 17....","[2.0, 50.0, 89.0, 56.2, 529.0, 6.4, 264.5, 44....","[3, 69, 115, 60.0, 769, 7.2, 256.3, 52, 4, 1, ...","[4, 93, 149, 62.4, 972, 7.1, 243.0, 52, 4, 1, ..."

Here you can see the resulting `df`. Each team has the played weeks as *columns* and the actual data-per-week as list. The name of the teams are the indices (as usual).

The next step is the last one: Simply create a variable (`pd.DataFrame()`) for each NFL Team.  
This DataFrame contains the following informations:
>```python
'GP', 'CMP', 'ATT', 'CMP%', 'YDS', 'AVG', 'YDS/G', 'LNG', 'TD', 'INT',
'SACK', 'SYL', 'RTG', 'ATT', 'YDS', 'AVG', 'YDS/G', 'LNG', 'TD', 'FUM',
'LST', 'NewEnglandPatriots'
```

The last column show the name of the team again and their results with the codec described [above](#importing-the-csv-files)

In [43]:
def create_team_report(data_base):
    
    ##############################
    ## INSERT CURRENT WEEK HERE ##
    ##############################
    
    current_week = 4
    
    ##############################
    ## INSERT CURRENT WEEK HERE ##
    ##############################
    
    for team in team_list:
            
            temp_team_df = pd.DataFrame(index=week0.columns)
            team_count = 1
            col_count = 0
            
            temp_team = data_base.loc[team]
            
            #return(temp_team)
            
            for week in range(current_week):
                temp_team_df.insert(col_count, 'week{}'.format(team_count), temp_team[col_count])
                col_count +=1
                team_count +=1
            
            team_temp_df_transpose = temp_team_df.transpose()
            
            globals()[team] = pd.concat([team_temp_df_transpose, scores_transpose[team]], axis=1)
            print('-'*30)
            print('Report is created for the {}'.format(temp_team.name))
            print('Report creation done!')
            print('#'*30)

In [44]:
create_team_report(results_df)

------------------------------
Report is created for the ArizonaCardinals
Report creation done!
##############################
------------------------------
Report is created for the AtlantaFalcons
Report creation done!
##############################
------------------------------
Report is created for the BaltimoreRavens
Report creation done!
##############################
------------------------------
Report is created for the BuffaloBills
Report creation done!
##############################
------------------------------
Report is created for the CarolinaPanthers
Report creation done!
##############################
------------------------------
Report is created for the ChicagoBears
Report creation done!
##############################
------------------------------
Report is created for the CincinnatiBengals
Report creation done!
##############################
------------------------------
Report is created for the ClevelandBrowns
Report creation done!
##############################
------------------------------
Report is created for the DallasCowboys
Report creation done!
##############################
------------------------------
Report is created for the DenverBroncos
Report creation done!
##############################
------------------------------
Report is created for the DetroitLions
Report creation done!
##############################
------------------------------
Report is created for the GreenBayPackers
Report creation done!
##############################
------------------------------
Report is created for the HoustonTexans
Report creation done!
##############################
------------------------------
Report is created for the IndianapolisColts
Report creation done!
##############################
------------------------------
Report is created for the JacksonvilleJaguars
Report creation done!
##############################
------------------------------
Report is created for the KansasCityChiefs
Report creation done!
##############################
------------------------------
Report is created for the LosAngelesChargers
Report creation done!
##############################
------------------------------
Report is created for the LosAngelesRams
Report creation done!
##############################
------------------------------
Report is created for the MiamiDolphins
Report creation done!
##############################
------------------------------
Report is created for the MinnesotaVikings
Report creation done!
##############################
------------------------------
Report is created for the NewEnglandPatriots
Report creation done!
##############################
------------------------------
Report is created for the NewOrleansSaints
Report creation done!
##############################
------------------------------
Report is created for the NewYorkGiants
Report creation done!
##############################
------------------------------
Report is created for the NewYorkJets
Report creation done!
##############################
------------------------------
Report is created for the OaklandRaiders
Report creation done!
##############################
------------------------------
Report is created for the PhiladelphiaEagles
Report creation done!
##############################
------------------------------
Report is created for the PittsburghSteelers
Report creation done!
##############################
------------------------------
Report is created for the SanFrancisco49ers
Report creation done!
##############################
------------------------------
Report is created for the SeattleSeahawks
Report creation done!
##############################
------------------------------
Report is created for the TampaBayBuccaneers
Report creation done!
##############################
------------------------------
Report is created for the TennesseeTitans
Report creation done!
##############################
------------------------------
Report is created for the WashingtonRedskins
Report creation done!
##############################

## Export the data

In [48]:
ArizonaCardinals.to_csv('./results_by_team/ArizonaCardinals')
AtlantaFalcons.to_csv('./results_by_team/AtlantaFalcons')
BaltimoreRavens.to_csv('./results_by_team/BaltimoreRavens')
BuffaloBills.to_csv('./results_by_team/BuffaloBills')
CarolinaPanthers.to_csv('./results_by_team/CarolinaPanthers')
ChicagoBears.to_csv('./results_by_team/ChicagoBears')
CincinnatiBengals.to_csv('./results_by_team/CincinnatiBengals')
ClevelandBrowns.to_csv('./results_by_team/ClevelandBrowns')
DallasCowboys.to_csv('./results_by_team/DallasCowboys')
DenverBroncos.to_csv('./results_by_team/DenverBroncos')
DetroitLions.to_csv('./results_by_team/DetroitLions')
GreenBayPackers.to_csv('./results_by_team/GreenBayPackers')
HoustonTexans.to_csv('./results_by_team/HoustonTexans')
IndianapolisColts.to_csv('./results_by_team/IndianapolisColts')
JacksonvilleJaguars.to_csv('./results_by_team/JacksonvilleJaguars')
KansasCityChiefs.to_csv('./results_by_team/KansasCityChiefs')
LosAngelesChargers.to_csv('./results_by_team/LosAngelesChargers')
LosAngelesRams.to_csv('./results_by_team/LosAngelesRams')
MiamiDolphins.to_csv('./results_by_team/MiamiDolphins')
MinnesotaVikings.to_csv('./results_by_team/MinnesotaVikings')
NewEnglandPatriots.to_csv('./results_by_team/NewEnglandPatriots')
NewOrleansSaints.to_csv('./results_by_team/NewOrleansSaints')
NewYorkGiants.to_csv('./results_by_team/NewYorkGiants')
NewYorkJets.to_csv('./results_by_team/NewYorkJets')
OaklandRaiders.to_csv('./results_by_team/OaklandRaiders')
PhiladelphiaEagles.to_csv('./results_by_team/PhiladelphiaEagles')
PittsburghSteelers.to_csv('./results_by_team/PittsburghSteelers')
SanFrancisco49ers.to_csv('./results_by_team/SanFrancisco49ers')
SeattleSeahawks.to_csv('./results_by_team/SeattleSeahawks')
TampaBayBuccaneers.to_csv('./results_by_team/TampaBayBuccaneers')
TennesseeTitans.to_csv('./results_by_team/TennesseeTitans')
WashingtonRedskins.to_csv('./results_by_team/WashingtonRedskins')